# Generated by Django 5.0.3 on 2024-03-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='don',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='don',
            name='category',
            field=models.CharField(blank=True, choices=[('photo', 'phone')], max_length=50, null=True),
        ),
    ]
