# Generated by Django 5.0.3 on 2024-03-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0002_alter_don_options_don_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
