# Generated by Django 5.0.3 on 2024-03-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0003_don_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
