# Generated by Django 5.0.3 on 2024-03-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0004_don_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='creted',
            field=models.DateTimeField(null=True),
        ),
    ]
