# Generated by Django 5.0.3 on 2024-03-26 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0005_don_creted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='category',
        ),
        migrations.RemoveField(
            model_name='don',
            name='content',
        ),
        migrations.RemoveField(
            model_name='don',
            name='creted',
        ),
        migrations.RemoveField(
            model_name='don',
            name='image',
        ),
        migrations.RemoveField(
            model_name='don',
            name='price',
        ),
        migrations.RemoveField(
            model_name='don',
            name='time',
        ),
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='don',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
